repeat task.wait() until game:IsLoaded()
pcall(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/edgeiy/infiniteyield/master/source", true))()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/7granddadpgn/vapev4forroblox/main/NewMainScript.lua", true))()
  end)