local lib = {}
local ch = game:GetService("CoreGui")
local NotificationSystem = Instance.new("ScreenGui", ch)
NotificationSystem.Name = "TestMenu"
--print(NotificationSystem)
--NotificaitonSystem.Parent = ch
local list = Instance.new("Frame")
local tweenService = game:GetService("TweenService")
local tweenInfo = TweenInfo.new
list.Parent = NotificationSystem
list.Name = "list"
list.AnchorPoint = Vector2.new(0.5, 0.5)
list.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
list.BackgroundTransparency = 1
list.BorderSizePixel = 0
list.Position = UDim2.new(0.911, 0, 0.522, 0)
list.Size = UDim2.new(0.178, 0, 0.869, 0)
list.Visible = true
local ls = Instance.new("UIListLayout")
ls.Name = "L"
ls.Parent = list
ls.HorizontalAlignment = Enum.HorizontalAlignment.Right
ls.SortOrder = Enum.SortOrder.LayoutOrder
ls.Padding = UDim.new(0, 5)
function lib:CreateNotification(typw, message, duration)
  if not table.find({ "error", "success", "info", "warning" }, typw:lower()) then return error("InvalidModeError: Invalid Mode Provided") end
  duration = tonumber(duration) or 5
  message = message or "Sonicware Loaded!"
  local x = typw:lower()
  local Notification
  if x == "error" then
    Error = Instance.new("Frame")
	  local UIGradient = Instance.new("UIGradient")
	  local Header = Instance.new("TextLabel")
	  local UITextSizeConstraint = Instance.new("UITextSizeConstraint")
	  local decal = Instance.new("Frame")
	  local icon = Instance.new("ImageLabel")
  	local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
  	local background_shadow = Instance.new("ImageLabel")
  	local UIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
  	local bar = Instance.new("Frame")
  	local Filler = Instance.new("Frame")
	  Error.Name = "Error"
	  Error.Parent = list
   	Error.AnchorPoint = Vector2.new(0.5, 0.5)
  	Error.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
  	Error.BorderSizePixel = 0
  	Error.Position = UDim2.new(0.5, 0, 0.109999999, 0)
  	Error.Size = UDim2.new(1, 0, 0.0860000029, 0)
	  UIGradient.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(31, 31, 31)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(39, 39, 39))}
	  UIGradient.Rotation = 25
	  UIGradient.Parent = Error
	  Header.Name = "Header"
	  Header.Parent = Error
	  Header.AnchorPoint = Vector2.new(0.5, 0.5)
	  Header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	  Header.BackgroundTransparency = 1.000
	  Header.BorderSizePixel = 0
	  Header.Position = UDim2.new(0.592000008, 0, 0.493999988, 0)
	  Header.Size = UDim2.new(0.788999975, 0, 0.648000002, 0)
	  Header.ZIndex = 2
	  Header.Font = Enum.Font.GothamBold
	  Header.Text = message
	  Header.TextColor3 = Color3.fromRGB(255, 70, 73)
	  Header.TextScaled = true
	  Header.TextSize = 14.000
	  Header.TextWrapped = true
	  Header.TextXAlignment = Enum.TextXAlignment.Left
    Header.TextYAlignment = Enum.TextYAlignment.Top
	  UITextSizeConstraint.Parent = Header
	  UITextSizeConstraint.MaxTextSize = 14
	  decal.Name = "decal"
	  decal.Parent = Error
	  decal.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	  decal.BackgroundTransparency = 1.000
	  decal.BorderSizePixel = 0
	  decal.Size = UDim2.new(1, 0, 1, 0)
	  decal.ZIndex = 0
	  icon.Name = "icon"
	  icon.Parent = decal
	  icon.AnchorPoint = Vector2.new(0.5, 0.5)
	  icon.BackgroundTransparency = 1.000
	  icon.BorderSizePixel = 0
	  icon.Position = UDim2.new(0.0900000036, 0, 0.485000014, 0)
	  icon.Size = UDim2.new(0.0900000036, 0, 0.485000014, 0)
	  icon.Image = "rbxassetid://7072725342"
	  icon.ImageColor3 = Color3.fromRGB(255, 70, 73)
  	icon.ScaleType = Enum.ScaleType.Fit
	  UIAspectRatioConstraint.Parent = icon
  	UIAspectRatioConstraint.AspectRatio = 1.008
  	background_shadow.Name = "background_shadow"
	  background_shadow.Parent = decal
	  background_shadow.AnchorPoint = Vector2.new(0.5, 0.5)
	  background_shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	  background_shadow.BackgroundTransparency = 1.000
	  background_shadow.BorderSizePixel = 0
	  background_shadow.Position = UDim2.new(0.5, 0, 0.5, 0)
	  background_shadow.Size = UDim2.new(1.12800705, 0, 1.86363637, 0)
	  background_shadow.ZIndex = 0
	  background_shadow.Image = "rbxassetid://3523728077"
  	background_shadow.ImageColor3 = Color3.fromRGB(24, 24, 24)
  	background_shadow.ImageTransparency = 0.700
	  UIAspectRatioConstraint_2.Parent = background_shadow
  	UIAspectRatioConstraint_2.AspectRatio = 2.669
  	bar.Name = "bar"
  	bar.Parent = Error
  	bar.AnchorPoint = Vector2.new(1, 0.5)
	  bar.BackgroundColor3 = Color3.fromRGB(255, 70, 73)
  	bar.BorderSizePixel = 0
	  bar.Position = UDim2.new(1, 0, 1, 0)
  	bar.Size = UDim2.new(0.00999999978, 0, 0.0500000007, 0)
  	bar.ZIndex = 3
  	Filler.Name = "Filler"
   	Filler.Parent = Error
	  Filler.AnchorPoint = Vector2.new(1, 0.5)
	  Filler.BackgroundColor3 = Color3.fromRGB(255, 70, 73)
	  Filler.BorderSizePixel = 0
	  Filler.Position = UDim2.new(1, 0, 0.5, 0)
	  Filler.Size = UDim2.new(0.0114559932, 0, 0.99999994, 0)
	  Filler.ZIndex = 3
    Notification = Error
  elseif x == "info" then
    local Info = Instance.new("Frame")
		local Header = Instance.new("TextLabel")
		local UITextSizeConstraint = Instance.new("UITextSizeConstraint")
		local UIGradient = Instance.new("UIGradient")
		local decal = Instance.new("Frame")
		local background_shadow = Instance.new("ImageLabel")
		local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
		local icon = Instance.new("ImageLabel")
		local UIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
		local Filler = Instance.new("Frame")
		local bar = Instance.new("Frame")
		Info.Name = "Info"
		Info.Parent = list
		Info.AnchorPoint = Vector2.new(0.5, 0.5)
		Info.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
		Info.BorderSizePixel = 0
		Info.Position = UDim2.new(0.5, 0, 0.109999999, 0)
		Info.Size = UDim2.new(1, 0, 0.0860000029, 0)
		Header.Name = "Header"
		Header.Parent = Info
		Header.AnchorPoint = Vector2.new(0.5, 0.5)
		Header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		Header.BackgroundTransparency = 1.000
		Header.BorderSizePixel = 0
		Header.Position = UDim2.new(0.592195153, 0, 0.494221866, 0)
		Header.Size = UDim2.new(0.788999975, 0, 0.648000002, 0)
		Header.ZIndex = 2
		Header.Font = Enum.Font.GothamBold
		Header.Text = message
		Header.TextColor3 = Color3.fromRGB(88, 101, 242)
		Header.TextScaled = true
		Header.TextSize = 14.000
		Header.TextWrapped = true
		Header.TextXAlignment = Enum.TextXAlignment.Left
		Header.TextYAlignment = Enum.TextYAlignment.Top
		UITextSizeConstraint.Parent = Header
		UITextSizeConstraint.MaxTextSize = 14
		UIGradient.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(31, 31, 31)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(39, 39, 39))}
		UIGradient.Rotation = 25
		UIGradient.Parent = Info
		decal.Name = "decal"
		decal.Parent = Info
		decal.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		decal.BackgroundTransparency = 1.000
		decal.BorderSizePixel = 0
		decal.Size = UDim2.new(1, 0, 1, 0)
		decal.ZIndex = 0
		background_shadow.Name = "background_shadow"
		background_shadow.Parent = decal
		background_shadow.AnchorPoint = Vector2.new(0.5, 0.5)
		background_shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		background_shadow.BackgroundTransparency = 1.000
		background_shadow.BorderSizePixel = 0
		background_shadow.Position = UDim2.new(0.5, 0, 0.5, 0)
		background_shadow.Size = UDim2.new(1.12800705, 0, 1.86363637, 0)
		background_shadow.ZIndex = 0
		background_shadow.Image = "rbxassetid://3523728077"
		background_shadow.ImageColor3 = Color3.fromRGB(24, 24, 24)
		background_shadow.ImageTransparency = 0.700
		UIAspectRatioConstraint.Parent = background_shadow
		UIAspectRatioConstraint.AspectRatio = 2.669
		icon.Name = "icon"
		icon.Parent = decal
		icon.AnchorPoint = Vector2.new(0.5, 0.5)
		icon.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
		icon.BackgroundTransparency = 1.000
		icon.BorderSizePixel = 0
		icon.Position = UDim2.new(0.089563109, 0, 0.485297441, 0)
		icon.Size = UDim2.new(0.0900000036, 0, 0.485000014, 0)
		icon.Image = "rbxassetid://7072717857"
		icon.ImageColor3 = Color3.fromRGB(88, 101, 242)
		icon.ScaleType = Enum.ScaleType.Fit
		UIAspectRatioConstraint_2.Parent = icon
		UIAspectRatioConstraint_2.AspectRatio = 1.008
		Filler.Name = "Filler"
		Filler.Parent = Info
		Filler.AnchorPoint = Vector2.new(1, 0.5)
		Filler.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
		Filler.BorderSizePixel = 0
		Filler.Position = UDim2.new(1, 0, 0.5, 0)
		Filler.Size = UDim2.new(0.0114559932, 0, 1, 0)
		Filler.ZIndex = 3
		bar.Name = "bar"
		bar.Parent = Info
		bar.AnchorPoint = Vector2.new(1, 0.5)
		bar.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
		bar.BorderSizePixel = 0
		bar.Position = UDim2.new(1, 0, 1, 0)
		bar.Size = UDim2.new(0.00999999978, 0, 0.0500000007, 0)
		bar.ZIndex = 3
    Notification = Info
  elseif x == "success" then
    local Success = Instance.new("Frame")
		local Header = Instance.new("TextLabel")
		local UITextSizeConstraint = Instance.new("UITextSizeConstraint")
		local UIGradient = Instance.new("UIGradient")
		local decal = Instance.new("Frame")
		local background_shadow = Instance.new("ImageLabel")
		local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
		local icon = Instance.new("ImageLabel")
		local UIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
		local Filler = Instance.new("Frame")
		local bar = Instance.new("Frame")
		Success.Name = "Success"
		Success.Parent = list
		Success.AnchorPoint = Vector2.new(0.5, 0.5)
		Success.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		Success.BorderSizePixel = 0
		Success.Position = UDim2.new(0.5, 0, 0.109999999, 0)
		Success.Size = UDim2.new(1, 0, 0.0860000029, 0)
		Header.Name = "Header"
		Header.Parent = Success
		Header.AnchorPoint = Vector2.new(0.5, 0.5)
		Header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		Header.BackgroundTransparency = 1.000
		Header.BorderSizePixel = 0
		Header.Position = UDim2.new(0.592000008, 0, 0.493999988, 0)
		Header.Size = UDim2.new(0.789030671, 0, 0.647699118, 0)
		Header.ZIndex = 2
		Header.Font = Enum.Font.GothamBold
		Header.Text = message
		Header.TextColor3 = Color3.fromRGB(35, 240, 110)
		Header.TextScaled = true
		Header.TextSize = 14.000
		Header.TextWrapped = true
		Header.TextXAlignment = Enum.TextXAlignment.Left
		Header.TextYAlignment = Enum.TextYAlignment.Top
		UITextSizeConstraint.Parent = Header
		UITextSizeConstraint.MaxTextSize = 14
		UIGradient.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(31, 31, 31)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(39, 39, 39))}
		UIGradient.Rotation = 25
		UIGradient.Parent = Success
		decal.Name = "decal"
		decal.Parent = Success
		decal.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		decal.BackgroundTransparency = 1.000
		decal.BorderSizePixel = 0
		decal.Size = UDim2.new(1, 0, 1, 0)
		decal.ZIndex = 0
		background_shadow.Name = "background_shadow"
		background_shadow.Parent = decal
		background_shadow.AnchorPoint = Vector2.new(0.5, 0.5)
		background_shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		background_shadow.BackgroundTransparency = 1.000
		background_shadow.BorderSizePixel = 0
		background_shadow.Position = UDim2.new(0.5, 0, 0.5, 0)
		background_shadow.Size = UDim2.new(1.12800705, 0, 1.86363637, 0)
		background_shadow.ZIndex = 0
		background_shadow.Image = "rbxassetid://3523728077"
		background_shadow.ImageColor3 = Color3.fromRGB(24, 24, 24)
		background_shadow.ImageTransparency = 0.700
		UIAspectRatioConstraint.Parent = background_shadow
		UIAspectRatioConstraint.AspectRatio = 2.669
		icon.Name = "icon"
		icon.Parent = decal
		icon.AnchorPoint = Vector2.new(0.5, 0.5)
		icon.BackgroundTransparency = 1.000
		icon.BorderSizePixel = 0
		icon.Position = UDim2.new(0.089563109, 0, 0.485297441, 0)
		icon.Size = UDim2.new(0.0900000036, 0, 0.485000014, 0)
		icon.Image = "http://www.roblox.com/asset/?id=6023426926"
		icon.ImageColor3 = Color3.fromRGB(35, 240, 110)
		icon.ScaleType = Enum.ScaleType.Fit
		UIAspectRatioConstraint_2.Parent = icon
		UIAspectRatioConstraint_2.AspectRatio = 1.008
		Filler.Name = "Filler"
		Filler.Parent = Success
		Filler.AnchorPoint = Vector2.new(1, 0.5)
		Filler.BackgroundColor3 = Color3.fromRGB(35, 240, 110)
		Filler.BorderSizePixel = 0
		Filler.Position = UDim2.new(1, 0, 0.5, 0)
		Filler.Size = UDim2.new(0.0114559932, 0, 1, 0)
		Filler.ZIndex = 3
		bar.Name = "bar"
		bar.Parent = Success
		bar.AnchorPoint = Vector2.new(1, 0.5)
		bar.BackgroundColor3 = Color3.fromRGB(35, 240, 110)
		bar.BorderSizePixel = 0
		bar.Position = UDim2.new(1, 0, 1, 0)
		bar.Size = UDim2.new(0.00999999978, 0, 0.0500000007, 0)
		bar.ZIndex = 3
    Notification = Success
  else
		local Warning = Instance.new("Frame")
		local Header = Instance.new("TextLabel")
		local UITextSizeConstraint = Instance.new("UITextSizeConstraint")
		local UIGradient = Instance.new("UIGradient")
		local decal = Instance.new("Frame")
		local background_shadow = Instance.new("ImageLabel")
		local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
		local icon = Instance.new("ImageLabel")
		local UIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
		local Filler = Instance.new("Frame")
		local bar = Instance.new("Frame")
		Warning.Name = "Warning"
		Warning.Parent = list
		Warning.AnchorPoint = Vector2.new(0.5, 0.5)
		Warning.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		Warning.BorderSizePixel = 0
		Warning.Position = UDim2.new(0.5, 0, 0.109999999, 0)
		Warning.Size = UDim2.new(1, 0, 0.0860000029, 0)
		Header.Name = "Header"
		Header.Parent = Warning
		Header.AnchorPoint = Vector2.new(0.5, 0.5)
		Header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		Header.BackgroundTransparency = 1.000
		Header.BorderSizePixel = 0
		Header.Position = UDim2.new(0.592000008, 0, 0.493999988, 0)
		Header.Size = UDim2.new(0.788999975, 0, 0.648000002, 0)
		Header.ZIndex = 2
		Header.Font = Enum.Font.GothamBold
		Header.Text = message
		Header.TextColor3 = Color3.fromRGB(240, 175, 45)
		Header.TextScaled = true
		Header.TextSize = 14.000
		Header.TextWrapped = true
		Header.TextXAlignment = Enum.TextXAlignment.Left
		Header.TextYAlignment = Enum.TextYAlignment.Top
		UITextSizeConstraint.Parent = Header
		UITextSizeConstraint.MaxTextSize = 14
		UIGradient.Color = ColorSequence.new{ColorSequenceKeypoint.new(0.00, Color3.fromRGB(31, 31, 31)), ColorSequenceKeypoint.new(1.00, Color3.fromRGB(39, 39, 39))}
		UIGradient.Rotation = 25
		UIGradient.Parent = Warning
		decal.Name = "decal"
		decal.Parent = Warning
		decal.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		decal.BackgroundTransparency = 1.000
		decal.BorderSizePixel = 0
		decal.Size = UDim2.new(1, 0, 1, 0)
		decal.ZIndex = 0
		background_shadow.Name = "background_shadow"
		background_shadow.Parent = decal
		background_shadow.AnchorPoint = Vector2.new(0.5, 0.5)
		background_shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
		background_shadow.BackgroundTransparency = 1.000
		background_shadow.BorderSizePixel = 0
		background_shadow.Position = UDim2.new(0.5, 0, 0.5, 0)
		background_shadow.Size = UDim2.new(1.12800705, 0, 1.86363637, 0)
		background_shadow.ZIndex = 0
		background_shadow.Image = "rbxassetid://3523728077"
		background_shadow.ImageColor3 = Color3.fromRGB(24, 24, 24)
		background_shadow.ImageTransparency = 0.700
		UIAspectRatioConstraint.Parent = background_shadow
		UIAspectRatioConstraint.AspectRatio = 2.669
		icon.Name = "icon"
		icon.Parent = decal
		icon.AnchorPoint = Vector2.new(0.5, 0.5)
		icon.BackgroundTransparency = 1.000
		icon.BorderSizePixel = 0
		icon.Position = UDim2.new(0.089563109, 0, 0.485297441, 0)
		icon.Size = UDim2.new(0.0900000036, 0, 0.485000014, 0)
		icon.Image = "rbxassetid://7072980286"
		icon.ImageColor3 = Color3.fromRGB(240, 175, 45)
		icon.ScaleType = Enum.ScaleType.Fit
		UIAspectRatioConstraint_2.Parent = icon
		UIAspectRatioConstraint_2.AspectRatio = 1.008
		Filler.Name = "Filler"
		Filler.Parent = Warning
		Filler.AnchorPoint = Vector2.new(1, 0.5)
		Filler.BackgroundColor3 = Color3.fromRGB(240, 175, 45)
		Filler.BorderSizePixel = 0
		Filler.Position = UDim2.new(1, 0, 0.5, 0)
		Filler.Size = UDim2.new(0.0114559932, 0, 1, 0)
		Filler.ZIndex = 3
		bar.Name = "bar"
		bar.Parent = Warning
		bar.AnchorPoint = Vector2.new(1, 0.5)
		bar.BackgroundColor3 = Color3.fromRGB(240, 175, 45)
		bar.BorderSizePixel = 0
		bar.Position = UDim2.new(1, 0, 1, 0)
		bar.Size = UDim2.new(0.00999999978, 0, 0.0500000007, 0)
		bar.ZIndex = 3
    Notification = Warning
  end
  Notification.Header.Text = message
  Notification.Header.RichText = true
  Notification.Size = UDim2.new(0, 0,0.087, 0)
  Notification.Filler.Size = UDim2.new(1, 0,1, 0)
  local n = tweenInfo(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 1, false, 0)
  local e = tweenInfo(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 1, false, 0)
  local x = tweenInfo(duration, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 1, false, 0)
  tweenService:Create(Notification, n, {
      Size = UDim2.new(1, 0,0.087, 0)
  }):Play()
  task.wait(0.2)
  tweenService:Create(Notification.Filler, e, {
      Size = UDim2.new(0.011, 0,1, 0)
  }):Play()
  tweenService:Create(Notification.bar, x, {
      Size = UDim2.new(1, 0,0.05, 0)
  }):Play()
  task.wait(duration)
  tweenService:Create(Notification.Filler, n, {
      Size = UDim2.new(1, 0,1, 0)
  }):Play()
  tweenService:Create(Notification, n, {
      Size = UDim2.new(0, 0,0.087, 0)
  }):Play()
  task.wait(.2)
  Notification:Destroy()
end
local ScreenGui = Instance.new("ScreenGui", ch)
ScreenGui.Name = "MainGui"
local Main = Instance.new("Frame")
local UICorner = Instance.new("UICorner")
local UIListLayout = Instance.new("UIListLayout")
local Title = Instance.new("TextLabel")
local Sep = Instance.new("Frame")
local Combat = Instance.new("TextButton")
local ImageLabel = Instance.new("ImageLabel")
local UITextSizeConstraint = Instance.new("UITextSizeConstraint")
local Blatant = Instance.new("TextButton")
local ImageLabel_2 = Instance.new("ImageLabel")
local UITextSizeConstraint_2 = Instance.new("UITextSizeConstraint")
local Render = Instance.new("TextButton")
local ImageLabel_3 = Instance.new("ImageLabel")
local UITextSizeConstraint_3 = Instance.new("UITextSizeConstraint")
local Utility = Instance.new("TextButton")
local ImageLabel_4 = Instance.new("ImageLabel")
local UITextSizeConstraint_4 = Instance.new("UITextSizeConstraint")
local World = Instance.new("TextButton")
local ImageLabel_5 = Instance.new("ImageLabel")
local UITextSizeConstraint_5 = Instance.new("UITextSizeConstraint")
local Settings = Instance.new("TextButton")
local ImageLabel_6 = Instance.new("ImageLabel")
local UITextSizeConstraint_6 = Instance.new("UITextSizeConstraint")
local HTU = Instance.new("TextButton")
local ImageLabel_7 = Instance.new("ImageLabel")
local UITextSizeConstraint_7 = Instance.new("UITextSizeConstraint")
local Credits = Instance.new("TextButton")
local ImageLabel_8 = Instance.new("ImageLabel")
local UITextSizeConstraint_8 = Instance.new("UITextSizeConstraint")
Main.Name = "Main"
Main.Parent = ScreenGui
Main.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
Main.BorderSizePixel = 0
Main.Position = UDim2.new(0.0215053782, 0, 0.0423076935, 0)
Main.Size = UDim2.new(0.140000001, 0, 0.449999988, 0)
Main.Visible = false
shared.drag(Main)
UICorner.CornerRadius = UDim.new(0, 4)
UICorner.Parent = Main
UIListLayout.Parent = Main
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout.Padding = UDim.new(0.00999999978, 0)
Title.Name = "Title"
Title.Parent = Main
Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title.BackgroundTransparency = 1.000
Title.Size = UDim2.new(1, 0, 0.100000001, 0)
Title.Font = Enum.Font.FredokaOne
Title.Text = "StarConfig"
Title.TextColor3 = Color3.fromRGB(200, 200, 200)
Title.TextScaled = true
Title.TextSize = 14.000
Title.TextStrokeColor3 = Color3.fromRGB(200, 200, 200)
Title.TextWrapped = true
Sep.Name = "Sep"
Sep.Parent = Main
Sep.BackgroundColor3 = Color3.fromRGB(200, 200, 200)
Sep.BackgroundTransparency = 0.600
Sep.BorderSizePixel = 0
Sep.Size = UDim2.new(1, 0, 0.00999999978, 0)
local ToggleUI = Instance.new("TextButton")
ToggleUI.Name = "ToggleUI"
ToggleUI.Parent = ScreenGui
ToggleUI.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
ToggleUI.BackgroundTransparency = 0.400
ToggleUI.BorderSizePixel = 0
ToggleUI.Position = UDim2.new(0.9195503, 0, 0.0673076957, 0)
ToggleUI.Size = UDim2.new(0.0799999982, 0, 0.0500000007, 0)
ToggleUI.Font = Enum.Font.FredokaOne
ToggleUI.Text = "Sonicware"
ToggleUI.TextColor3 = Color3.fromRGB(200, 200, 200)
ToggleUI.TextSize = 14.000
local function PHNSHGK_fake_script() -- ToggleUI.LocalScript 
	local script = Instance.new('LocalScript', ToggleUI)

	script.Parent.MouseButton1Click:Connect(function()
		for i, v in pairs(script.Parent.Parent:GetChildren()) do
			if v:IsA("Frame") then
				pcall(function() v.Visible = not v.Visible end)
			end
		end
	end)
end
coroutine.wrap(PHNSHGK_fake_script)()
lib["MainGui"] = ScreenGui
lib["ObjectsThatCanBeSaved"] = {}
function lib:CreateWindow(title)
  local Combat = Instance.new("Frame")
  local ReturnValue = {
    ["Gui"] = Combat,
    ["Api"] = {
      ["Toggle"] = function(tg)
        Combat.Visible = tg
      end,
      ["Destroy"] = function()
        Combat:Destroy() 
        lib.ObjectsThatCanBeSaved[title.."Window"] = nil
      end
    }
  }
  local UICorner = Instance.new("UICorner")
  local Title = Instance.new("TextLabel")
  local Sep = Instance.new("Frame")
  local List = Instance.new("ScrollingFrame")
  local UIListLayout = Instance.new("UIListLayout")
  local UIListLayout_2 = Instance.new("UIListLayout")
  Combat.Name = title
  shared.drag(Combat)
  Combat.Parent = ScreenGui
  Combat.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
  Combat.BorderSizePixel = 0
  Combat.Position = UDim2.new(0.16921407, 0, 0.0419999994, 0)
  Combat.Size = UDim2.new(0.140000001, 0, 0.449999988, 0)
  Combat.Visible = false
  UICorner.CornerRadius = UDim.new(0, 4)
  UICorner.Parent = Combat
  Title.Name = "Title"
  Title.Parent = Combat
  Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
  Title.BackgroundTransparency = 1.000
  Title.Position = UDim2.new(-0.254154414, 0, 0, 0)
  Title.Size = UDim2.new(1, 0, 0.100000001, 0)
  Title.Font = Enum.Font.FredokaOne
  Title.Text = title
  Title.TextColor3 = Color3.fromRGB(200, 200, 200)
  Title.TextScaled = true
  Title.TextSize = 14.000
  Title.TextStrokeColor3 = Color3.fromRGB(200, 200, 200)
  Title.TextWrapped = true
  Sep.Name = "Sep"
  Sep.Parent = Combat
  Sep.BackgroundColor3 = Color3.fromRGB(200, 200, 200)
  Sep.BackgroundTransparency = 0.600
  Sep.BorderSizePixel = 0
  Sep.Size = UDim2.new(1, 0, 0.00999999978, 0)
  List.Name = "List"
  List.Parent = Combat
  List.Active = true
  List.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
  List.BackgroundTransparency = 1.000
  List.Position = UDim2.new(0.0586510226, 0, -0.176923081, 0)
  List.Size = UDim2.new(1, 0, 0.860000014, 0)
  List.CanvasSize = UDim2.new(0, 0, 0, 0)
  UIListLayout.Parent = List
  UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
  local btns = {}
  function ReturnValue['Api']:CreateToggle(text)
    local Toggle = Instance.new("TextButton")
    Toggle.Name = "Toggle"
    Toggle.Parent = List
    Toggle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    Toggle.BorderSizePixel = 0
    Toggle.Size = UDim2.new(1, 0, 0.150000006, 0)
    Toggle.Style = Enum.ButtonStyle.RobloxButton
    Toggle.Font = Enum.Font.FredokaOne
    Toggle.Text = text
    Toggle.TextColor3 = Color3.fromRGB(200, 200, 200)
    Toggle.TextSize = 20.000
    return Toggle
  end
  lib.ObjectsThatCanBeSaved[title.."Window"] = ReturnValue
  return ReturnValue['Api']
end
shared.GUI = lib